### ISSUE TITLE
Bug: env file missing after initial repo clone

### ISSUE THREAD

**Issue by PlesnikJakub** [3PillarGlobal-Czechia/interview-app-ui#14]
After the initial repository clone, there is no .env file. 
This file should contain so far only URL to backend API but with time I do expect there will be more values.

**Proposed solution A**
keep the .env file in .gitignore but create a file called .env.example that will contain example values and instructions to create .env locally. 

**Proposed solution B**
Follow react documentation and put .env back into git but write down instructions for creating a .env.local for its override.

https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

Note: keep in mind that local .env can differ, .env file will be also used in other environments (dev,prod) and probably created inserted by pipeline.

**Comment by petrspelos** [comment]
In case anyone wants to setup their local environment for testing purposes and is looking for this file, the contents of the `.env` file are:

```
REACT_APP_BACKEND_URL=https://localhost:5001
```

**Comment by PlesnikJakub** [comment]
resolved
