### ISSUE TITLE
UseCase: Question selection

### ISSUE THREAD

**Issue by PlesnikJakub** [3PillarGlobal-Czechia/interview-app-ui#5]
## User story
As an **Interviewer**, 
I want to be able to **select multiple questions** from the view,
so that I can **use them for an interview**.

## Additional information
The question selection page should contain a list of questions and the ability to filter through them by 

* difficulty
* category
* full text

Users should be able to see already selected questions anytime during the selection process. ( AntD Drawer? 🤔 )

**Comment by PlesnikJakub** [comment]
Hi @petrspelos, this one needs a design and will be one of the first we will implement on UI. The most important area of this task is to make UI clean and possibly display only relevant information for an interviewer. Please, don't get tied up by the use of "list" in the description. If there is any other structure you would recommend I am open to it 😊

**Comment by petrspelos** [comment]
@PlesnikJakub I'll get this ready ASAP, current ETA end of this week.

I'll post any updates in #4
