### ISSUE TITLE
UseCase: Interview

### ISSUE THREAD

**Issue by PlesnikJakub** [3PillarGlobal-Czechia/interview-app-ui#6]
Implement interview page. 

After starting the interview from the Question list page, this view should contain additional options for purpose of leading the interview.

**Comment by PlesnikJakub** [comment]
@petrspelos we need to design how the interview page should look like. 
The interview page is the page when the interview is in progress. 

Questions must be visible - with all metadata, like description, answer, difficulty. 
The question block needs to contain tools - Find similar questions, rate answers, skip questions.

**Comment by petrspelos** [comment]
Will do, chief! 🦺 🪖

**Comment by TomasNiemczyk98** [comment]
On hold until design is available

**Comment by TomasNiemczyk98** [comment]
I will start on this and then the page can go through 2nd iteration to improve the design
